/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface GithubCard {
    'user': string;
  }
  interface GithubCardAttributes extends StencilHTMLAttributes {
    'user'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GithubCard': Components.GithubCard;
  }

  interface StencilIntrinsicElements {
    'github-card': Components.GithubCardAttributes;
  }


  interface HTMLGithubCardElement extends Components.GithubCard, HTMLStencilElement {}
  var HTMLGithubCardElement: {
    prototype: HTMLGithubCardElement;
    new (): HTMLGithubCardElement;
  };

  interface HTMLElementTagNameMap {
    'github-card': HTMLGithubCardElement
  }

  interface ElementTagNameMap {
    'github-card': HTMLGithubCardElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
